export default {
    content: [
        './components/**/*.{vue,js}',
        './pages/**/*.vue',
        './app.vue'
    ],
    theme: {
        extend: {
            colors: {
                'on-tertiary-container': '#636565',
                'border-subtle': '#1A1A1A',
                'primary': '#ffffff',
                'badge-success-border': '#166534',
                'on-primary-fixed-variant': '#454747',
                'surface-dim': '#141313',
                'inverse-surface': '#e5e2e1',
                'on-primary-fixed': '#1a1c1c',
                'success': '#22C55E',
                'tertiary-fixed-dim': '#c6c6c7',
                'on-secondary-fixed': '#1c1b1b',
                'primary-fixed-dim': '#c6c6c7',
                'on-error-container': '#ffdad6',
                'surface-container-highest': '#353434',
                'destructive': '#FF4444',
                'tertiary-fixed': '#e2e2e2',
                'secondary-fixed-dim': '#c9c6c5',
                'on-secondary': '#313030',
                'text-secondary': '#888888',
                'on-primary-container': '#636565',
                'tertiary-container': '#e2e2e2',
                'badge-error-border': '#7F1D1D',
                'secondary': '#c9c6c5',
                'badge-success-bg': '#052E16',
                'on-error': '#690005',
                'on-tertiary-fixed-variant': '#454747',
                'bg-primary': '#000000',
                'outline': '#8e9192',
                'primary-fixed': '#e2e2e2',
                'background': '#141313',
                'surface-container-lowest': '#0e0e0e',
                'secondary-container': '#4a4949',
                'surface-tint': '#c6c6c7',
                'on-tertiary-fixed': '#1a1c1c',
                'on-secondary-fixed-variant': '#474646',
                'error': '#ffb4ab',
                'bg-tertiary': '#111111',
                'surface-container': '#201f1f',
                'surface-container-low': '#1c1b1b',
                'on-secondary-container': '#bab8b7',
                'on-background': '#e5e2e1',
                'text-tertiary': '#555555',
                'border-default': '#222222',
                'on-surface': '#e5e2e1',
                'surface': '#141313',
                'on-surface-variant': '#c4c7c8',
                'border-active': '#444444',
                'tertiary': '#ffffff',
                'secondary-fixed': '#e5e2e1',
                'surface-container-high': '#2a2a2a',
                'inverse-primary': '#5d5f5f',
                'inverse-on-surface': '#313030',
                'badge-error-bg': '#1A0000',
                'surface-bright': '#3a3939',
                'error-container': '#93000a',
                'surface-variant': '#353434',
                'text-primary': '#FFFFFF',
                'on-tertiary': '#2f3131',
                'outline-variant': '#444748',
                'primary-container': '#e2e2e2',
                'on-primary': '#2f3131',
                'bg-secondary': '#0A0A0A',
                'app-bg': '#000000',
                'app-card': '#0A0A0A',
                'app-input': '#111111',
                'app-border': '#222222',
                'app-border-subtle': '#1A1A1A',
                'app-border-active': '#444444',
            },
            fontFamily: {
                body: ['Inter'],
                mono: ['Space Grotesk'],
                heading: ['Inter'],
                label: ['Inter'],
                avatar: ['Inter'],
                sans: ['Inter', 'ui-sans-serif', 'system-ui'],
            }
        }
    }
}
